#- History
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt inc_append_history histignorealldups

#- Completion
autoload -Uz compinit && compinit

# Colored and interactive menu
eval "$(dircolors)"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu select

autoload -Uz select-word-style && select-word-style bash

#- Editor
export EDITOR="nvim"

#- Aliases
alias snvim='sudo nvim'
alias nrs='sudo nixos-rebuild switch'
alias ff='fastfetch'
alias ll='ls -la'

#- Prompt

PROMPT="> "
RPROMPT="%F{red}%?%f %~"

setopt prompt_subst

