#!/usr/bin/env python3

import argparse
from pathlib import Path
import random
import subprocess
import sys

# Variables
cache_dir = Path.home() / ".cache" / "wallpaperutil"
image_name = "frame.jpg"

util_name = "wallpaperutil"

image_types = {"jpg", "jpeg", "png", "bmp", "webp"}
video_types = {"mp4", "mkv", "webm", "avi"}

log_level = 1

def log(log, level=1):
    if log_level >= level:
        print(f"[ {util_name} ]  {log}")

def run_cmd(cmd):
    match log_level:
        case 0:
            subprocess.run(cmd, stdout=subprocess.DEVNULL, check=True)
        case 1:
            subprocess.run(cmd, stdout=subprocess.DEVNULL, check=True)
        case 2:
            subprocess.run(cmd, check=True)

def getType(file):
    log(f"Getting type of file: {file} ...", 2)

    ext = file.suffix.lower().lstrip(".")

    if ext in image_types:
        return "image"
    elif ext in video_types:
        return "video"
    else:
        log(f"couldn't match file as video or image", 2)
        return None

def setWallpaper(file):
    log("Setting wallpaper...")
    run_cmd(["waypaper", "--wallpaper", str(file)])

def setColor(file, backend):
    log(f"Starting {backend} to generate colors...")
    match backend:
        case "wal":
            run_cmd(["wal", "-i", str(file), "-n"])
        case "wallust":
            run_cmd(["wallust", "run", str(file)])

def extractImage(file):
    log(f"Extracting image from {file} ...")
    run_cmd(["mpv", "--vo=image", "--frames=1", str(file), "--volume=0"])
    output = cache_dir/image_name
    run_cmd(["mv", "-f", "00000001.jpg", str(output)])
    return cache_dir/image_name

def pickRandomFile(directory):
    files = []

    for file in directory.rglob("*"):
        if file.is_file():
            file_type = getType(file)
            
            if file_type:
                files.append(file)

    if not files:
        log("No valid media files found!", 0)
        sys.exit(2)

    return random.choice(files)

def main():
    global log_level
    cache_dir.mkdir(parents=True, exist_ok=True)

    parser = argparse.ArgumentParser(
        prog=util_name,
        description="A wallpaper and colorscheme utility for Wayland.",
        epilog=f"""
Examples:
    {util_name} -f ~/Wallpapers/cat.png -b wallust
    {util_name} -f Wallpapers/dog.mpv --backend wal
    {util_name} -r ~/Wallpapers/ --log-level 0
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument("-l", "--log-level", choices=[0, 1, 2], default=1, type=int,
                        help="Set logging verbosity (0-quiet, 1-normal, 2-verbose), default: 1")
    parser.add_argument("-b", "--backend", choices=["wal", "wallust"], default="wallust",
                        help="Backend to use for color extraction, default: wallust")
    parser.add_argument("-f", "--file", type=Path, metavar="FILE",
                        help="File to set as wallpaper")
    parser.add_argument("-r", "--random", type=Path, metavar="DIR",
                        help="Pick a random file from the given directory")

    args = parser.parse_args()

    # setup variables
    file = pickRandomFile(args.random) if args.random else args.file
    log_level = args.log_level

    if not file:
        parser.print_help()
        sys.exit(0)

    log(f"selected file: {file}")

    if args.random and args.file:
        log(f"{args.file} overwritten by random selection!", 0)

    image = file
    file_type = getType(file)
    if file_type == "video":
        image = extractImage(file)
    elif file_type != "image":
        log(f"{file} isn't a valid image or video file!", 0)
        sys.exit(2)
    
    try:
        setColor(image, args.backend)
        setWallpaper(file)
    except subprocess.CalledProcessError as e:
        log(f"command failed: {e}", 0)
        sys.exit(1)
        
    log("Success!")

if __name__ == "__main__":
    main()
