general {
    gaps_in = 0
    gaps_out = 2
    border_size = 1
    col.active_border = rgba(00000000)
    col.inactive_border = rgba(59595900)
    resize_on_border = false
    allow_tearing = false
    layout = master
}
