monitor=,preferred,auto,auto

$terminal = kitty
$fileManager = kitty -- yazi
$menu = rofi -show drun

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = XCURSOR_THEME,Bibata-Original-Classic 
env = HYPRCURSOR_THEME,Bibata-Original-Classic

# exec-once = mpvpaper -o "no-audio loop" -f ALL ~/Wallpapers/
# exec-once = wal -R
exec = env PATH=$HOME/.local/bin:$PATH wallpaperutil -f ~/Wallpapers/niko-fish.mp4
exec-once = wayle panel start

source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decorations.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/layouts.conf
source = ~/.config/hypr/misc-inputs.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/windowrules.conf


