[styling.palette]
bg = "#070305"
surface = "#0A0408"
elevated = "#0A0408"
fg = "#B2C4D4"
fg-muted = "#A0B1C1"
primary = "#503D8E"
red = "#4A3458"
yellow = "#782F55"
green = "#7A5539"
blue = "#503D8E"

