foreground         #B2C4D4
background         #070305
cursor             #A494AE

active_tab_foreground     #070305
active_tab_background     #B2C4D4
inactive_tab_foreground   #B2C4D4
inactive_tab_background   #070305

color0       #0A0408
color8       #677786
color1       #4A3458
color9       #523962
color2       #7A5539
color10      #906240
color3       #782F55
color11      #8C3262
color4       #503D8E
color12      #5C44AB
color5       #914B7B
color13      #9B4682
color6       #496883
color14      #456889
color7       #A0B1C1
color15      #C7D0D8

