foreground         #DACAD0
background         #0C0007
cursor             #B17F96

active_tab_foreground     #0C0007
active_tab_background     #DACAD0
inactive_tab_foreground   #DACAD0
inactive_tab_background   #0C0007

color0       #241921
color8       #87777D
color1       #9B4784
color9       #C051A1
color2       #893A5F
color10      #A3406F
color3       #6E305B
color11      #7F3468
color4       #75406F
color12      #89497F
color5       #4D365B
color13      #573B66
color6       #904C66
color14      #994867
color7       #C1ABB3
color15      #C1ABB3

