font_family	Iosevka
font_size	12

disable_ligatures always

cursor			none
cursor_shape		beam
cursor_shape_unfocused 	underline

cursor_stop_blinking_after 0

enable_audio_bell 	no
confirm_os_window_close 0

foreground #ffffff
background #000000
background_opacity	0.9

window_padding_width	10
window_padding_height	 7
